config/routes.rb
Rails.application.routes.draw do
  resources :activities
  root 'prototype#index'
  get 'beta_sign_in' => 'prototype#sign_in', as: :sign_in
  get 'beta_sign_up' => 'prototype#sign_up', as: :sign_up
  get 'main' => 'prototype#main'
  get 'subjects' => 'prototype#subjects_index', as: :subjects
  get 'subject/23' => 'prototype#subject_show', as: :show_subject

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  validates :title, :description, :start_time, :end_time, :location, :organizer, :related_link, presence: true
end

app/models/settings.rb
class Settings < Settingslogic
  source "#{Rails.root}/config/application.yml"
  namespace Rails.env
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]
  
  # GET /activities
  # GET /activities.json
  def index
    @activities = Activity.all
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(activity_params)

    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, notice: 'Activity was successfully created.' }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url, notice: 'Activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.require(:activity).permit(:title, :description, :start_time, :end_time, :location, :organizer, :related_link)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/prototype_controller.rb
  class PrototypeController < ApplicationController

    def index
    end

    def sign_in
    end

    def sign_up
    end

    def main
    end

    def subjects_index
    end

    def subject_show
    end

  end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/prototype_helper.rb
module PrototypeHelper
end

app/views/activities/_form.html.erb
 <div class="row">
  <%= simple_form_for(@activity) do |f| %>
    <%= f.error_notification %>

    <div class="row">
      <div class="input-field col s6">
        <%= f.input :title %>
      </div>
      <div class="input-field col s12">
        <%= f.input :description, as: :text %>
      </div>
      <div class="input-field col s6">
        <%= f.date_field(:start_time) %>
      </div>
      <div class="input-field col s6">
        <%= f.date_field(:end_time) %>
      </div>
      <div class="input-field col s12">
        <%= f.input :location %>
      </div>
      <div class="input-field col s12">
        <%= f.input :organizer %>
      </div>
      <div class="input-field col s12">
        <%= f.input :related_link, as: :url %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.button :submit %>
    </div>
  <% end %>
  </div>
</div>


<script>
  $('.datepicker').pickadate({
    selectMonths: true, // Creates a dropdown to control month
    selectYears: 15 // Creates a dropdown of 15 years to control year
  });  
</script>

app/views/activities/edit.html.erb
<h1>Editing Activity</h1>

<%= render 'form' %>

<%= link_to 'Show', @activity %> |
<%= link_to 'Back', activities_path %>

app/views/activities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Activities</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Location</th>
      <th>Organizer</th>
      <th>Related link</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @activities.each do |activity| %>
      <tr>
        <td><%= activity.title %></td>
        <td><%= activity.description %></td>
        <td><%= activity.start_time %></td>
        <td><%= activity.end_time %></td>
        <td><%= activity.location %></td>
        <td><%= activity.organizer %></td>
        <td><%= activity.related_link %></td>
        <td><%= link_to 'Show', activity %></td>
        <td><%= link_to 'Edit', edit_activity_path(activity) %></td>
        <td><%= link_to 'Destroy', activity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Activity', new_activity_path %>

app/views/activities/new.html.erb
<h1>New Activity</h1>

<%= render 'form' %>

<%= link_to 'Back', activities_path %>

app/views/activities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @activity.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @activity.description %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @activity.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @activity.end_time %>
</p>

<p>
  <strong>Location:</strong>
  <%= @activity.location %>
</p>

<p>
  <strong>Organizer:</strong>
  <%= @activity.organizer %>
</p>

<p>
  <strong>Related link:</strong>
  <%= @activity.related_link %>
</p>

<%= link_to 'Edit', edit_activity_path(@activity) %> |
<%= link_to 'Back', activities_path %>

app/views/common/_GA.html.erb
<!-- Google Analystic -->
  <script>
    (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
    function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
    e=o.createElement(i);r=o.getElementsByTagName(i)[0];
    e.src='//www.google-analytics.com/analytics.js';
    r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
    ga('create','UA-XXXXX-X','auto');ga('send','pageview');
  </script>

app/views/common/_footer.html.erb
<!-- footer -->
<footer class="main-footer">
  <span>Copyright © 2005-2014 Joinfuns. All Rights Reserved.</span>
</footer>

app/views/common/_header.html.erb
<!-- header -->
<nav class="main-navibar">
  <%= link_to main_path, class: 'logo-wrapper', :'data-no-turbolink' => true do %>
    <%= image_tag 'logo-white@2x.png' %>
  <% end %>

  <div class="main-menu">
    <ul>
      <li><%= link_to 'Subject', subjects_path %></li>
      <li><a href="#">Create New</a></li>
      <li class='user-menu-trigger'>
        <a href="#">
          <div class="user-avatar">
            <%= image_tag 'avatar-placeholder.gif', class: 'responsive-img circle' %>
          </div>
          <span class="user-name">UserName</span>
        </a>
      </li>
    </ul>
  </div>
</nav>

<div class="main-function-bar-wrapper">
  <div class="filter-trigger">
    <span>Filter</span><i class="material-icons right">expand_more</i>
  </div>
  <form action="#">
    <div class="search-form-wrapper">
      <div class="search-form-input">
        <input type="text" placeholder="Title | DM | Time | Subject">
      </div>
      <div class="search-button">
        <button><i class="material-icons left">search</i> Search</button>
      </div>
    </div>
  </form>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>JoinFuns :: 探索身邊的新鮮事</title>
    <meta name="description" content="DESCRIPTION">
    <meta name="viewport" content="width=1280">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= javascript_include_tag 'modernizr' %>

  </head>
  <body class='<%= "#{controller.controller_name}-#{controller.action_name}" %>'>
      <!--[if lt IE 7]>
          <p class="chromeframe">You are using an outdated browser. <a href="http://browsehappy.com/">Upgrade your browser today</a> or <a href="http://www.google.com/chromeframe/?redirect=true">install Google Chrome Frame</a> to better experience this site.</p>
      <![endif]-->

  <div class="application-container" style="background-image: url(<%= asset_url('landing-bg-2560.jpg') %>);">
    <%= yield %>
  </div>

  <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
  <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true, 'data-turbolinks-eval' => true %>
  <%= yield :handwrite_js %>

  </body>
</html>

app/views/prototype/index.html.erb
<div class="landing-login-options-wrapper">
  <div class="logo">
    <%= image_tag 'logo@2x.png', class: 'responsive-img' %>
  </div>

  <div class="login-options-wrapper">
    <%= link_to main_path, class: 'facebook trans-03s', :'data-no-turbolink' => true do %>
      <span>Sign in with Facebook</span>
    <% end %>
    <%= link_to sign_in_path, class: 'email trans-03s' do %>
      <span>Sign in with Email</span>
    <% end %>
  </div>
</div>

app/views/prototype/main.html.erb
<%= render partial: 'common/header' %>

<!-- map canvas -->
<div class="map-canvas" id="map"></div>

<!-- user position marker -->
<div class="user-position-marker">
  <a href="#"></a>
  <div class="i-am-here">
    <span>Hey! I'm Here!</span>
  </div>
</div>

<!-- panels -->

<div class="filter-panel-wrapper trans-03s">
  <form action="#">
    <!-- Distance -->
    <div class="filter-section-wrapper">
      <div class="filter-section">
        <h4>Distance</h4>
        <p class="range-field">
          <input type="range" min="0.0" max="10.0" />
        </p>
        <span>0km</span><span class="right">10km</span>
      </div>
      <div class="filter-section">
        <input placeholder="Type Address" type="text">
      </div>
    </div>

    <!-- Active Type -->
    <div class="filter-section-wrapper">
      <div class="filter-section">
        <h4>Active Type</h4>
        <div class="input-field">
          <select>
            <option value="0">All Category</option>
            <option value="1">Eat</option>
            <option value="2">Play</option>
            <option value="3">Charity</option>
            <option value="4">Education</option>
          </select>
        </div>
      </div>
      <div class="filter-section">
        <input placeholder="Type Keyword" type="text">
      </div>
      <div class="filter-section">
        <a href="#">Food<i class="material-icons right">chevron_right</i></a>
      </div>
    </div>

    <!-- Time -->
    <div class="filter-section-wrapper">
      <div class="filter-section">
        <h4>Time</h4>
        <div class="input-field">
          <select>
            <option value="0">Recently</option>
            <option value="1">in 2 weeks</option>
            <option value="2">in 1 month</option>
            <option value="3">in 6 month</option>
          </select>
        </div>
      </div>
    </div>

    <!-- Price -->
    <div class="filter-section-wrapper">
      <div class="filter-section">
        <h4>Price</h4>
        <div class="input-field">
          <select>
            <option value="0">Free</option>
            <option value="1">1 ~ 299</option>
            <option value="2">Over 300</option>
          </select>
        </div>
      </div>
    </div>

    <div class="filter-section-wrapper">
      <div class="filter-submit-btn">
        <button type='submit' class="btn">Submit</button>
      </div>
    </div>
  </form>
</div>

<!-- event markers -->
<% rand(1..8).times.each do %>
  <div class="event-demo" style="top: <%= rand(10..45) %>%; left: <%= rand(10..45) %>%;"></div>
<% end %>

<!-- dm markers -->
<% rand(1..8).times.each do %>
  <div class="dm-demo" style="top: <%= rand(55..90) %>%; left: <%= rand(55..90) %>%;"></div>
<% end %>

<%= render partial: 'common/footer' %>

<%= content_for :handwrite_js do %>
  <script>
    $(document).ready(JoinFuns.initialMap());
    $(document).ready(JoinFuns.initMaterialSelect());
    $(document).ready(JoinFuns.filterTriggerInit());
  </script>
<% end %>

app/views/prototype/sign_in.html.erb
<div class="landing-sign-in-form-wrapper">
  <div class="logo">
    <%= image_tag 'logo@2x.png', class: 'responsive-img' %>
  </div>

  <div class="sign-in-form">
    <div class="form">
      <form action="#">
        <div class="input-field">
          <input placeholder="Username" type="text" class="validate">
        </div>
        <div class="input-field">
          <input placeholder="Password" type="password" class="validate">
        </div>

        <%= link_to main_path, class: 'submit-btn', :'data-no-turbolink' => true do %>
          <span>Sign in</span>
        <% end %>
        <!--
        <div class="submit-btn">
          <button>
            Sign in
          </button>
        </div>
        -->
      </form>
    </div>
  </div>

  <div class="sign-up-option-wrapper">
    <a href="#"><i class="material-icons left">help_outline</i> forget password</a>
  </div>
</div>

<div class="landing-divider"></div>

<div class="landing-sign-up-link">
  <span>Don't have an account? <%= link_to 'Sign up', sign_up_path %></span>
</div>

app/views/prototype/sign_up.html.erb
<div class="landing-sign-up-form-wrapper">
  <div class="logo">
    <%= image_tag 'logo@2x.png', class: 'responsive-img' %>
  </div>

  <div class="user-avatar">
    <%= image_tag 'avatar-placeholder.gif', class: 'responsive-img circle' %>
  </div>

  <form action="#">
    <div class="user-name">
      <input type="text" value='John Doe' placeholder="Enter Your Name Here">
    </div>
    <div class="file-field input-field">
      <div class="btn select-photo">
        <span>change photo</span>
        <input type="file">
      </div>
      <div class="file-path-wrapper">
        <input class="file-path validate" type="text">
      </div>
    </div>

    <div class="sign-up-form">
      <div class="input-field">
        <input placeholder="Email" type="text" class="validate">
      </div>
      <div class="input-field">
        <input placeholder="Password" type="password" class="validate">
      </div>
      <div class="input-field">
        <input placeholder="Confirm Password" type="password" class="validate">
      </div>
      <div class="input-field">
        <input placeholder="Cell Phone" type="tel" class="validate">
      </div>
      <div class="input-field">
        <input placeholder="Birthday" type="text" class="validate">
      </div>
      <div class="subscribe">
        <p>
          <input type="checkbox" id="test" checked="checked" />
          <label for="test">Subscribe News</label>
        </p>
      </div>

      <%= link_to main_path, class: 'submit-btn', :'data-no-turbolink' => true do %>
        <span>GO!</span>
      <% end %>
      <!--
      <div class="submit-btn">
        <button>
          Sign in
        </button>
      </div>
      -->

    </div>
  </form>

app/views/prototype/subject_show.html.erb
<%= render partial: 'common/header' %>

<div class="subject-detail-wrapper">
  <div class="subjects-container">
    <div class="navigation-option">
      <%= link_to '< Back To List', subjects_path, class: 'back-to-list waves-effect waves-light btn left' %>
    </div>

    <div class="subject-info-banner">
      <div class="picture-cover">
        <%= image_tag 'subject-detail-banner.jpg', class: 'responsive-img' %>
      </div>
      <div class="info-detail">
        <h3>Groningen</h3>

        <div class="points-info">
          <span>單標點數：</span><span> <%= rand(1..50) %> 點</span>
        </div>

        <div class="product-link">
          <a href="#">商品來源連結</a>
        </div>

        <div class="progress-info-wrapper">
          <span>標案進度：</span>
          <div class="progress">
            <% progress = rand(5..100) %>
            <div class="determinate" style="width: <%= progress %>%"></div>
          </div>
          <span class="progress-value">
            <%= progress %>%
          </span>
        </div>

        <span>截標時間：</span>
        <div class="time-info-wrapper">
          <div class="hour">
            <span class='value'><%= rand(0..23).to_s.rjust(2, '0') %></span>
            <span class="unit">hr</span>
          </div>
          <div class="minute">
            <span class='value'><%= rand(0..59).to_s.rjust(2, '0') %></span>
            <span class="unit">min</span>
          </div>
          <div class="second">
            <span class='value'><%= rand(0..59).to_s.rjust(2, '0') %></span>
            <span class="unit">sec</span>
          </div>
        </div>

        <form action="#">
          <div class="input-field col s6">
            <input placeholder="" id="first_name" type="number" class="validate">
            <label for="first_name">下標點數</label>
          </div>
          <button type="submit" class="btn">下標</button>
        </form>
      </div>
    </div>
  </div>
  <div class="subject-description-wrapper subjects-container">
    <span>詳細資訊</span>
    <h4>Groningen</h4>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Culpa consectetur non atque mollitia numquam neque nulla quae facere illum ab ea veniam eveniet rerum iste temporibus aliquid, fugiat doloremque ipsam sint! Modi qui repellendus aliquam, illum inventore odit sapiente adipisci doloribus perspiciatis, nesciunt velit dolores nostrum. Enim praesentium eveniet esse omnis eius, cum ipsam! Repellendus veritatis ratione ipsum labore numquam fugit ex quidem consequatur, dolore! Doloremque, dolorem at nesciunt repellendus nisi et aspernatur tempora. Commodi, quidem voluptatum consequuntur maiores cumque esse velit! Ut, neque quaerat dolorem, minima praesentium quas vitae eos illo fugiat inventore dolorum, harum obcaecati, nisi quasi ipsam.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ea facilis quo rerum nam modi sunt sed id accusantium magnam perspiciatis recusandae quae iste, nihil ab officia, qui, quidem consectetur odio nemo ipsam animi obcaecati quas. Facere, nemo, debitis. Libero quo tenetur, ipsa laborum, rerum doloremque vel repudiandae iure accusantium quia adipisci sit omnis dolor minima itaque nam, aliquam iste corporis quis magni. Dicta vel in velit eius accusantium nesciunt odit porro similique laudantium, quam quisquam dignissimos magni voluptatibus, nemo saepe. Quisquam modi placeat quidem voluptates eaque rem laudantium velit adipisci facilis consequuntur, tempora odio cupiditate perferendis debitis esse non harum sequi error unde id. Officia quisquam corrupti, nesciunt, blanditiis fugiat quaerat ab. Odio deleniti obcaecati ab aspernatur amet corporis, laborum atque expedita, iusto eos et quidem, recusandae consequatur voluptatum maiores corrupti animi exercitationem labore sunt sit adipisci! Totam ducimus atque, sapiente quaerat sunt, velit aut repellat! Facere consequuntur repellat praesentium modi dignissimos non similique, quae voluptatum amet, perspiciatis ipsum dolores nesciunt nisi inventore, fugit! Porro enim adipisci officia aperiam non, doloremque reiciendis voluptas, qui omnis. Explicabo obcaecati iure et nesciunt ea, facilis expedita quod doloremque, non veritatis consequatur libero iste ducimus, cumque laudantium similique id a fugiat dolor est fugit.</p>
  </div>
</div>

<%= render partial: 'common/footer' %>

app/views/prototype/subjects_index.html.erb
<%= render partial: 'common/header' %>

<div class="subjects-index-wrapper">
  <div class="subjects-container">
    <% 20.times.each do %>
      <div class="subject-unit">
        <div class="subject-inner trans-03s">
          <div class="subject-cover-wrapper" style="background-image: url(<%= asset_url('subject-cover.jpg') %>);"></div>
          <div class="subject-info-wrapper">
            <h3>Groningen</h3>

            <div class="progress">
              <% progress = rand(5..100) %>
              <div class="determinate" style="width: <%= progress %>%"></div>
            </div>
            <span class="progress-value">
              <%= progress %>%
            </span>

            <div class="time-info-wrapper">
              <div class="hour">
                <span class='value'><%= rand(0..23).to_s.rjust(2, '0') %></span>
                <span class="unit">hr</span>
              </div>
              <div class="minute">
                <span class='value'><%= rand(0..59).to_s.rjust(2, '0') %></span>
                <span class="unit">min</span>
              </div>
              <div class="second">
                <span class='value'><%= rand(0..59).to_s.rjust(2, '0') %></span>
                <span class="unit">sec</span>
              </div>
            </div>

            <div class="get-button">
              <%= link_to 'Get', show_subject_path %>
              <!-- <a href="#">Get</a> -->
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<%= render partial: 'common/footer' %>